/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet MT3620 Starter Kit (SK) to the
// 'project hardware' abstraction used by this project.
// Some peripherals are on-board on the Avnet MT3620 SK, while other peripherals must be attached externally if needed.

// This file is autogenerated from ..\..\project_hardware.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk.h"

// MT3620 SK: User Button A.
#define PROJECT_BUTTON_1 AVNET_MT3620_SK_USER_BUTTON_A

// MT3620 SK: User Button B.
#define PROJECT_BUTTON_2 AVNET_MT3620_SK_USER_BUTTON_B

// MT3620 SK: User LED.
#define PROJECT_LED AVNET_MT3620_SK_USER_LED_RED

// MT3620 SK: User LED RED Channel.
#define PROJECT_RGBLED_RED AVNET_MT3620_SK_USER_LED_RED

// MT3620 SK: User LED GREEN Channel.
#define PROJECT_RGBLED_GREEN AVNET_MT3620_SK_USER_LED_GREEN

// MT3620 SK: User LED BLUE Channel.
#define PROJECT_RGBLED_BLUE AVNET_MT3620_SK_USER_LED_BLUE

// MT3620 SK: Connect SOCKET1 RX (RX) to SOCKET1 TX (TX).
#define PROJECT_UART AVNET_MT3620_SK_ISU0_UART

// MT3620 SK: SOCKET1, SOCKET2, GROVE & OLED I2C ISU.
#define PROJECT_ISU2_I2C AVNET_MT3620_SK_ISU2_I2C

// MT3620 SK: SOCKET1 & SOCKET2 INT pin.
#define PROJECT_GPIO2 AVNET_MT3620_SK_GPIO2

